### ISSUE TITLE
Python3.12运行demo.py报错，tshark版本4.2.5，已加环境变量

### ISSUE THREAD

**Issue by jiandandan** [Byxs20/FlowAnalyzer#4]
"C:\Program Files\Python312\python.exe" C:\Users\Administrator\Desktop\FlowAnalyzer-main\tests\demo.py 
[Waring/Error]: b"'tshark' \xb2\xbb\xca\xc7\xc4\xda\xb2\xbf\xbb\xf2\xcd\xe2\xb2\xbf\xc3\xfc\xc1\xee\xa3\xac\xd2\xb2\xb2\xbb\xca\xc7\xbf\xc9\xd4\xcb\xd0\xd0\xb5\xc4\xb3\xcc\xd0\xf2\r\n\xbb\xf2\xc5\xfa\xb4\xa6\xc0\xed\xce\xc4\xbc\xfe\xa1\xa3\r\n"
Traceback (most recent call last):

**Comment by Byxs20** [comment]
![image](https://github.com/user-attachments/assets/d933ba2b-dafa-4018-bb50-4d6f65d0f73b)
改好环境变量重启IDE
